services:
  - type: web
    name: katalden-api
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && NODE_ENV=production npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    domains:
      - api.mauriciolacerda.com
    envVars:
      - key: PUBLIC_SERVER_URL
        sync: false
      - key: PUBLIC_ADMIN_URL
        sync: false
      - key: NODE_VERSION
        value: ~16.17.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
  - type: web
    name: katalden-admin
    env: static
    plan: free
    buildCommand: npm install && NODE_ENV=production npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /*
        destination: /index.html
    domains:
      - admin.mauriciolacerda.com
    envVars:
      - key: PUBLIC_SERVER_URL
        sync: false
      - key: PUBLIC_ADMIN_URL
        sync: false
      - key: NODE_VERSION
        value: ~16.17.0
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: strapi-db
    plan: free
